
export const techStackOptions = [
    "JavaScript",
    "TypeScript",
    "React",
    "Next.js",
    "Node.js",
    "Python",
    "Java",
    "C#",
    "Go",
    "Rust",
    "PHP",
    "Ruby",
    "Swift",
    "Kotlin",
    "Dart",
    "Flutter",
    "React Native",
    "Vue.js",
    "Angular",
    "Svelte",
    "Express.js",
    "FastAPI",
    "Django",
    "Flask",
    "Spring Boot",
    "Laravel",
    "Rails",
    "ASP.NET",
    "GraphQL",
    "REST API",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Firebase",
    "Supabase",
    "Prisma",
    "Sequelize",
    "TypeORM",
    "Jest",
    "Cypress",
    "Playwright",
    "Tailwind CSS",
    "Bootstrap",
    "Material-UI",
    "Chakra UI",
    "Ant Design",
  ]
  
  export const countries = [
    "United States",
    "Canada",
    "United Kingdom",
    "Germany",
    "France",
    "Spain",
    "Italy",
    "Netherlands",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Switzerland",
    "Austria",
    "Belgium",
    "Ireland",
    "Portugal",
    "Poland",
    "Czech Republic",
    "Hungary",
    "Romania",
    "Bulgaria",
    "Croatia",
    "Slovenia",
    "Slovakia",
    "Estonia",
    "Latvia",
    "Lithuania",
    "Australia",
    "New Zealand",
    "Japan",
    "South Korea",
    "Singapore",
    "India",
    "China",
    "Brazil",
    "Argentina",
    "Chile",
    "Mexico",
    "South Africa",
    "Israel",
    "Turkey",
    "Russia",
    "Ukraine",
    "Other",
  ]

  export const occupations = [
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "DevOps Engineer",
    "Data Scientist",
    "Data Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "Mobile Developer",
    "Game Developer",
    "Web Developer",
    "UI/UX Designer",
    "Product Manager",
    "Project Manager",
    "Technical Lead",
    "Engineering Manager",
    "CTO",
    "CEO/Founder",
    "Freelancer",
    "Student",
    "Bootcamp Graduate",
    "Career Changer",
    "Consultant",
    "Other",
  ]